### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by karuju** [karuju/Graduation-exam#21]
### 実装予定の機能
- [ ] ユーザー登録(閲覧は誰でも可能)<br>
- [ ] スレッドの作成…好きな音楽を投稿する<br>
- [ ] 回答...投稿に対して回答する<br>
- [ ] 投稿...スレッドとは別で、好きなコンテンツと音楽を紹介する投稿
- [ ] 検索<br>
- [ ] お気に入り<br>
- [ ] 投稿された曲をSpotifyやYoutubeから取得してリンクを表示する<br>
- [ ] シェア...スレッドと投稿ごとにシェアボタンを作る
- [ ] リスト...好きなアーティストをリストに入れる

### トップページ
- [ ] トップページ
- [ ] ログインページ
- [ ] ユーザー登録ページ
- [ ] パスワード再設定
- [ ] ユーザープロフィール詳細
- [ ] ユーザープロフィール編集
- [ ] 検索結果一覧
- [ ] スレッド作成
- [ ] スレッド編集
- [ ] スレッド一覧
- [ ] スレッド詳細/回答一覧
- [ ] 回答作成
- [ ] 回答編集
- [ ] 投稿作成
- [ ] 投稿編集
- [ ] 投稿詳細
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お気に入り一覧
- [ ] アーティストリスト

**Comment by karuju** [comment]
すみません、URLが間違っておりましたので再提出いたします。
ご確認お願いいたします。

**Comment by Tsuchiya2** [comment]
Projectsに移動して看板を確認しようとしたところ、閲覧できなかったのでご連絡です。

カリキュラムに掲載されているリンクを確認いただき、他者が看板・issue・ストーリポイントを確認できる状態にしてください。よろしくお願いいたします。

<img width="880" alt="スクリーンショット 2023-11-27 11 35 15" src="https://github.com/karuju/Graduation-exam/assets/61481161/0e085756-8377-40c9-abf6-7822ac478fa0">

**Comment by karuju** [comment]
コメントありがとうございました。
たびたびすみません、こちらで大丈夫でしょうか？
ご確認お願いいたします。

**Comment by shota-hope** [comment]
ありがとうございます。LGTMです！
